name: proksee
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- fastp=0.23.2
- skesa=2.4.0
- mash=2.3
- quast=5.0.2
- scipy
- spades=3.15.5
- wget
- pip
- pip:
  - .
  - numpy==1.19.5
  - scikit-learn==0.24.1
  - joblib==1.0.1
